"""roles and refresh tokens

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-20 13:11:38.628781

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=32), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    # --- справочник ролей ---
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
    )
    op.bulk_insert(
        roles_table,
        [
            {"id": 1, "name": "student", "description": "Takes courses"},
            {"id": 2, "name": "teacher", "description": "Authors and sells courses"},
            {"id": 3, "name": "moderator", "description": "Reviews content and appeals"},
            {"id": 4, "name": "admin", "description": "Administers the platform"},
            {"id": 5, "name": "owner", "description": "Platform owner"},
        ],
    )
    # Последовательность id должна продолжиться после вставленных вручную строк,
    # иначе следующая роль получит id=1 и вставка упадёт.
    op.execute("SELECT setval('roles_id_seq', (SELECT MAX(id) FROM roles))")

    # --- перенос данных: старая колонка -> user_roles ---
    # Выполняется ДО удаления колонки, иначе роли существующих пользователей
    # теряются безвозвратно. На пустой базе просто ничего не делает.
    op.execute(
        """
        INSERT INTO user_roles (user_id, role_id, granted_at)
        SELECT u.id, r.id, NOW()
        FROM users u
        JOIN roles r ON r.name = u.role
        ON CONFLICT DO NOTHING
        """
    )
    # Роли аддитивны: у всех должен быть student, включая преподавателей.
    op.execute(
        """
        INSERT INTO user_roles (user_id, role_id, granted_at)
        SELECT u.id, 1, NOW() FROM users u
        ON CONFLICT DO NOTHING
        """
    )

    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True))
    # Восстанавливаем одну роль на пользователя — самую привилегированную,
    # потому что колонка вмещает только одну. Часть данных при откате теряется,
    # это неизбежно при схлопывании many-to-many в одно поле.
    op.execute(
        """
        UPDATE users u SET role = sub.name FROM (
            SELECT ur.user_id, r.name,
                   ROW_NUMBER() OVER (PARTITION BY ur.user_id ORDER BY r.id DESC) AS rn
            FROM user_roles ur JOIN roles r ON r.id = ur.role_id
        ) sub
        WHERE sub.user_id = u.id AND sub.rn = 1
        """
    )
    op.execute("UPDATE users SET role = 'student' WHERE role IS NULL")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
