"""real task test cases

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-20 13:58:21.063314

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("starter_code", sa.Text(), nullable=True),
        sa.Column("reference_solution", sa.Text(), nullable=True),
        sa.Column("time_limit_ms", sa.Integer(), nullable=False),
        sa.Column("memory_limit_mb", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_languages_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_languages")),
        sa.UniqueConstraint("task_id", "language", name="uq_task_languages_task_language"),
    )
    op.create_index(op.f("ix_task_languages_task_id"), "task_languages", ["task_id"], unique=False)
    op.create_table(
        "test_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("stdin", sa.Text(), nullable=True),
        sa.Column("expected_stdout", sa.Text(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("ordering", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_test_cases_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
    )
    op.create_index(op.f("ix_test_cases_task_id"), "test_cases", ["task_id"], unique=False)
    op.create_table(
        "submission_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("test_case_id", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("actual_stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("time_ms", sa.Integer(), nullable=True),
        sa.Column("memory_kb", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_results_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
            name=op.f("fk_submission_results_test_case_id_test_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_results")),
    )
    op.create_index(
        op.f("ix_submission_results_submission_id"),
        "submission_results",
        ["submission_id"],
        unique=False,
    )
    op.add_column("submissions", sa.Column("language", sa.String(length=32), nullable=True))
    op.add_column("submissions", sa.Column("tests_passed", sa.Integer(), nullable=False))
    op.add_column("submissions", sa.Column("tests_total", sa.Integer(), nullable=False))
    op.add_column("submissions", sa.Column("score", sa.Float(), nullable=False))
    op.add_column("tasks", sa.Column("comparison", sa.String(length=20), nullable=False))
    op.add_column("tasks", sa.Column("float_tolerance", sa.Float(), nullable=False))
    op.drop_column("tasks", "expected_output")
    op.drop_column("tasks", "test_cases")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("test_cases", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "tasks", sa.Column("expected_output", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("tasks", "float_tolerance")
    op.drop_column("tasks", "comparison")
    op.drop_column("submissions", "score")
    op.drop_column("submissions", "tests_total")
    op.drop_column("submissions", "tests_passed")
    op.drop_column("submissions", "language")
    op.drop_index(op.f("ix_submission_results_submission_id"), table_name="submission_results")
    op.drop_table("submission_results")
    op.drop_index(op.f("ix_test_cases_task_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_index(op.f("ix_task_languages_task_id"), table_name="task_languages")
    op.drop_table("task_languages")
    # ### end Alembic commands ###
