"""course slug

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-20 16:12:35.618354

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("slug", sa.String(length=80), nullable=True))
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_column("courses", "slug")
    # ### end Alembic commands ###
