"""Реэкспорт: `from app.models import User` продолжает работать."""

from app.schemas.ai import (
    AICourseGenerateRequest,
    AIPromptRequest,
    AIPromptResponse,
    AIResumeCheckRequest,
)
from app.schemas.auth import (
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    SessionResponse,
    UserResponse,
    UserUpdate,
)
from app.schemas.course import (
    CourseCardResponse,
    CourseCreate,
    CourseOutlineResponse,
    CourseResponse,
    LessonCreate,
    LessonResponse,
    ModuleCreate,
    ModuleResponse,
    TaskCreate,
    TaskResponse,
)
from app.schemas.gamification import (
    AchievementResponse,
    FlashcardCreate,
    FlashcardResponse,
    FlashcardReview,
    LeaderboardEntry,
    PurchaseRequest,
    StoreItemResponse,
    StreakResponse,
    UserAchievementResponse,
)
from app.schemas.integrity import (
    AppealCreate,
    AppealResponse,
)
from app.schemas.learning import (
    HintRequest,
    HintResponse,
    PeerReviewCreate,
    PeerReviewResponse,
    ProgressCreate,
    ProgressResponse,
    RunRequest,
    RunResponse,
    SubmissionResponse,
    SubmitRequest,
    TestOutcomeResponse,
)
from app.schemas.social import (
    ClanCreate,
    ClanResponse,
    CommentCreate,
    CommentResponse,
    MessageCreate,
    MessageResponse,
    NotificationResponse,
)

__all__ = [
    "AICourseGenerateRequest",
    "AIPromptRequest",
    "AIPromptResponse",
    "AIResumeCheckRequest",
    "AchievementResponse",
    "AppealCreate",
    "AppealResponse",
    "ClanCreate",
    "ClanResponse",
    "CommentCreate",
    "CommentResponse",
    "CourseCardResponse",
    "CourseCreate",
    "CourseOutlineResponse",
    "CourseResponse",
    "FlashcardCreate",
    "FlashcardResponse",
    "FlashcardReview",
    "HintRequest",
    "HintResponse",
    "LeaderboardEntry",
    "LessonCreate",
    "LessonResponse",
    "LoginRequest",
    "MessageCreate",
    "MessageResponse",
    "ModuleCreate",
    "ModuleResponse",
    "NotificationResponse",
    "PeerReviewCreate",
    "PeerReviewResponse",
    "ProgressCreate",
    "ProgressResponse",
    "PurchaseRequest",
    "RefreshRequest",
    "RegisterRequest",
    "RunRequest",
    "RunResponse",
    "SessionResponse",
    "StoreItemResponse",
    "StreakResponse",
    "SubmissionResponse",
    "SubmitRequest",
    "TaskCreate",
    "TaskResponse",
    "TestOutcomeResponse",
    "UserAchievementResponse",
    "UserResponse",
    "UserUpdate",
]
